from django.urls import path

from sao.views import (
    home,
    del_employee_hour,
    employee_hour_view,
    modify_record,
    attendance_summary,
    employee_list,
    add_employee,
    edit_employee,
    leave_from_company,
    cancel_leave_from_company,
    employee_record,
    staff_detail,
    time_clock,
    permission,
    modify_permission,
    holiday_settings,
    delete_holiday,
    progress,
    update_annual_leave,
    download_csv,
    web_timestamp_view,
    add_steppingout,
    modify_steppingout,
    del_steppingout,
    change_stamp_id,
    get_employee_json,
    working_hours_view,
    add_working_hours,
    del_working_hours,
    update_working_hours,
    day_switch_time_view,
    day_switch_time_edit,
    day_switch,
    setup_sample_data,
    generate_sample_data,
    employee_attendance_detail,
    time_clock_detail,
    sample_stamp,
    clear_stamp,
)

app_name = "sao"
urlpatterns = [
    path("", home, name="home"),
    # 雇用者に割り当てる勤務時間
    path(
        "employee_hour/<id>/delete",
        del_employee_hour,
        name="del_employee_hour",
    ),
    path(
        "employee_hour/<int:employee_no>",
        employee_hour_view,
        name="employee_hour_view",
    ),
    path(
        "modify_record/<int:pk>/<int:year>/<int:month>/",
        modify_record,
        name="modify_record",
    ),
    path("attendance_summary/", attendance_summary, name="attendance_summary"),
    # 雇用者管理
    path("employee/", employee_list, name="employee_list"),
    path("employee/add", add_employee, name="add_employee"),
    path("employee/<int:employee_no>/edit", edit_employee, name="edit_employee"),
    path(
        "employee/<int:employee_no>/leave",
        leave_from_company,
        name="leave_from_company",
    ),
    path(
        "employee/<int:employee_no>/cancel_leave",
        cancel_leave_from_company,
        name="cancel_leave_from_company",
    ),
    path(
        "staff_detail/<employee>/<int:year>/<int:month>/",
        staff_detail,
        name="staff_detail",
    ),
    path("time_clock/", time_clock, name="time_clock"),
    path("permission/", permission, name="permission"),
    path(
        "permission/<int:user_id>/edit",
        modify_permission,
        name="modify_permission",
    ),
    path("holiday_settings/", holiday_settings, name="holiday_settings"),
    path("holiday/<int:id>/delete", delete_holiday, name="delete_holiday"),
    path("progress/<int:pk>/", progress, name="progress"),  # 進捗が表示されていくペー
    path("update_annual_leave", update_annual_leave, name="update_annual_leave"),
    path(
        "download_csv/<int:employee_no>/<int:year>/<int:month>",
        download_csv,
        name="download_csv",
    ),
    path(
        "webtimestamp/<int:employee_no>/",
        web_timestamp_view,
        name="web_timestamp_view",
    ),
    path(
        "add_steppingout/<int:record>/<int:year>/<int:month>",
        add_steppingout,
        name="add_steppingout",
    ),
    path(
        "modify_steppingout/<int:steppingout>/<int:record>/<int:year>/<int:month>",
        modify_steppingout,
        name="modify_steppingout",
    ),
    path(
        "dep_steppingout/<int:steppingout>/<int:record>/<int:year>/<int:month>",
        del_steppingout,
        name="del_steppingout",
    ),
    path("change_stamp_id", change_stamp_id, name="change_stamp_id"),
    path("get_employee_json", get_employee_json, name="get_employee_json"),
    path("working_hours/", working_hours_view, name="working_hours_view"),
    path("working_hours/add", add_working_hours, name="add_working_hours"),
    path("working_hours/<int:id>/delete/", del_working_hours, name="del_working_hours"),
    path(
        "working_hours/<int:id>/update/",
        update_working_hours,
        name="edit_working_hours",
    ),
    path("day_switch_time_view/", day_switch_time_view, name="day_switch_time_view"),
    path(
        "day_switch_time_edit/<int:id>/",
        day_switch_time_edit,
        name="day_switch_time_edit",
    ),
    path("day_switch", day_switch, name="day_switch"),
    path(
        "employee_attendance_detail/<int:employee_no>/<int:year>/<int:month>/",
        employee_attendance_detail,
        name="employee_attendance_detail",
    ),
    path("employee_record/", employee_record, name="employee_record"),
    path(
        "time_clock_detail/<int:employee_no>/",
        time_clock_detail,
        name="time_clock_detail",
    ),
    # for sample data
    path("generate_sample_data", generate_sample_data, name="generate_sample_data"),
]
