FROM python:3.11-slim

# 必要なパッケージをインストール
RUN apt-get update && apt-get install -y \
    libmariadb-dev \
    pkg-config \
    default-mysql-client \
    gcc \
    && apt-get clean

# Djangoアプリのコピーと依存関係のインストール
WORKDIR /app
COPY . /app
RUN pip install -r requirements.txt

ENTRYPOINT ["tools/docker-entrypoint.sh"]
