# Generated by Django 5.0.3 on 2025-09-03 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('sao', '0001_squashed_0010_permission_enable_view_executive_section_page'), ('sao', '0011_remove_permission_enable_view_executive_section_page'), ('sao', '0012_remove_permission_enable_access_secomcard'), ('sao', '0013_remove_permission_enable_import_time_record'), ('sao', '0014_delete_reminder'), ('sao', '0015_remove_timerecord_extra_code'), ('sao', '0016_remove_timerecord_achievementfrom_and_more'), ('sao', '0017_remove_timerecord_eval_code_timerecord_status'), ('sao', '0018_remove_timerecord_flag'), ('sao', '0019_rename_fromtime_timerecord_clock_in_and_more'), ('sao', '0020_rename_totime_timerecord_clock_out'), ('sao', '0021_rename_accepted_overtime_timerecord_is_overtime_work_permitted'), ('sao', '0022_alter_employee_department_and_more'), ('sao', '0023_rename_holiday_holiday_date'), ('sao', '0024_remove_timerecord_rawfrom_remove_timerecord_rawto'), ('sao', '0025_remove_timerecord_accepted_overwork_fromtime_and_more'), ('sao', '0026_workinghour_is_active'), ('sao', '0027_rename_appliedofficehours_employeehour'), ('sao', '0028_dayswitchtime'), ('sao', '0029_rename_timerecord_employeedailyrecord')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=20)),
                ('payed_holiday', models.FloatField()),
                ('join_date', models.DateField()),
                ('leave_date', models.DateField()),
                ('employee_type', models.IntegerField(choices=[(0, '正社員'), (1, '派遣社員'), (2, '業務委託')], default=0)),
                ('department', models.IntegerField(choices=[(0, '一般'), (1, '開発')], default=0)),
                ('include_overtime_pay', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sao.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_date', models.DateField(verbose_name='申請日')),
                ('category', models.IntegerField(choices=[('1', '残業'), ('2', '有給休暇'), ('3', '代休届'), ('4', '生理休暇'), ('5', '慶弔休暇'), ('6', '特別休暇'), ('7', '欠勤'), ('8', '遅刻'), ('9', '早退'), ('10', '私用外出'), ('11', '出張'), ('12', '休日出勤')])),
                ('begin_date', models.DateField(verbose_name='開始日時')),
                ('begin_time', models.TimeField(verbose_name='開始時間')),
                ('end_date', models.DateField(verbose_name='終了日時')),
                ('end_time', models.TimeField(verbose_name='終了時間')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sao.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDailyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clock_in', models.DateTimeField(blank=True, null=True)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('is_overtime_work_permitted', models.BooleanField(default=False)),
                ('remark', models.CharField(blank=True, max_length=128, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sao.employee')),
                ('status', models.IntegerField(blank=True, choices=[(0, '未確定'), (1, '勤務'), (2, '欠勤'), (3, '休日'), (4, '休出（法定）'), (27, '休出（法定）午前休'), (14, '休出（法定）午後休（休息なし）'), (15, '休出（法定）午後休（休息あり）'), (5, '休出（法定外）'), (28, '休出（法定外）午前休'), (16, '休出（法定外）午後休（休息なし）'), (17, '休出（法定外）午後休（休息あり）'), (6, '有休'), (18, '有休-午前休'), (19, '有休-午後休（休息なし）'), (20, '有休-午後休（休息あり）'), (7, '代休'), (21, '代休-午前休'), (22, '代休-午後休（休息なし）'), (23, '代休-午後休（休息あり）'), (8, '特別休'), (24, '特別休-午前休'), (25, '特別休-午後休（休息なし）'), (26, '特別休-午後休（休息あり）'), (12, 'その他'), (13, '予定')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10, unique=True, verbose_name='区分')),
                ('begin_time', models.TimeField(verbose_name='出社時間')),
                ('end_time', models.TimeField(verbose_name='退社時間')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sao.employee')),
                ('working_hours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sao.workinghour')),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0, verbose_name='進捗')),
                ('status', models.IntegerField(default=0, verbose_name='ステータス')),
                ('message', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebTimeStamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sao.employee')),
                ('stamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SteppingOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_time', models.DateTimeField(blank=True, null=True)),
                ('return_time', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sao.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_stamp_on_web', models.BooleanField(default=False)),
                ('enable_view_detail', models.BooleanField(default=True)),
                ('enable_view_temporary_staff_record', models.BooleanField(default=False)),
                ('enable_view_dev_staff_record', models.BooleanField(default=False)),
                ('enable_view_outsource_staff_record', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('enable_regist_event', models.BooleanField(default=False)),
                ('enable_add_staff', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DaySwitchTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
