# Generated by Django 2.0 on 2019-08-21 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    # replaces = [('sao', '0001_initial'), ('sao', '0002_auto_20170131_1141'), ('sao', '0003_holiday'), ('sao', '0004_timerecord_comment'), ('sao', '0005_remove_timerecord_comment'), ('sao', '0006_reminder'), ('sao', '0007_auto_20170217_1610'), ('sao', '0008_auto_20170217_1815'), ('sao', '0009_auto_20170217_1855'), ('sao', '0010_auto_20170220_1519'), ('sao', '0011_remove_reminder_submitted'), ('sao', '0012_secomcard'), ('sao', '0013_auto_20170414_1651'), ('sao', '0014_auto_20170414_1653'), ('sao', '0015_auto_20170414_1745'), ('sao', '0016_secomcardrecord'), ('sao', '0017_auto_20170414_1809'), ('sao', '0018_auto_20170424_1351'), ('sao', '0019_auto_20170424_1357'), ('sao', '0020_auto_20170424_1358'), ('sao', '0021_auto_20170424_1359'), ('sao', '0022_auto_20170424_1431'), ('sao', '0023_auto_20170424_1433'), ('sao', '0024_auto_20170424_1959'), ('sao', '0025_auto_20170424_2017'), ('sao', '0026_employee_status'), ('sao', '0027_remove_employee_status'), ('sao', '0028_auto_20170426_1609'), ('sao', '0029_auto_20170426_1611'), ('sao', '0030_auto_20170427_1332'), ('sao', '0031_auto_20170427_1333'), ('sao', '0032_auto_20170427_1913'), ('sao', '0033_auto_20180207_1516'), ('sao', '0034_progress'), ('sao', '0035_foo'), ('sao', '0036_auto_20180402_1507'), ('sao', '0037_permission_enable_access_secomcard'), ('sao', '0038_permission_enable_regist_event'), ('sao', '0039_auto_20180611_1651')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedOfficeHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('payed_holiday', models.FloatField()),
                ('join_date', models.DateField()),
                ('leave_date', models.DateField()),
                ('employee_type', models.IntegerField(default=0)),
                ('department', models.IntegerField(default=0)),
                ('include_overtime_pay', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sao.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_date', models.DateField(verbose_name='申請日')),
                ('category', models.IntegerField(choices=[('1', '残業'), ('2', '有給休暇'), ('3', '代休届'), ('4', '生理休暇'), ('5', '慶弔休暇'), ('6', '特別休暇'), ('7', '欠勤'), ('8', '遅刻'), ('9', '早退'), ('10', '私用外出'), ('11', '出張'), ('12', '休日出勤')])),
                ('begin_date', models.DateField(verbose_name='開始日時')),
                ('begin_time', models.TimeField(verbose_name='開始時間')),
                ('end_date', models.DateField(verbose_name='終了日時')),
                ('end_time', models.TimeField(verbose_name='終了時間')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sao.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_stamp_on_web', models.BooleanField(default=False)),
                ('enable_view_detail', models.BooleanField(default=True)),
                ('enable_view_temporary_staff_record', models.BooleanField(default=False)),
                ('enable_view_dev_staff_record', models.BooleanField(default=False)),
                ('enable_view_outsource_staff_record', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('enable_access_secomcard', models.BooleanField(default=False)),
                ('enable_regist_event', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TimeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fromTime', models.DateTimeField(blank=True, null=True)),
                ('rawFrom', models.CharField(blank=True, max_length=16, null=True)),
                ('toTime', models.DateTimeField(blank=True, null=True)),
                ('rawTo', models.CharField(blank=True, max_length=16, null=True)),
                ('achievementFrom', models.DateTimeField(blank=True, null=True)),
                ('achievementTo', models.DateTimeField(blank=True, null=True)),
                ('flag', models.CharField(max_length=8)),
                ('eval_code', models.IntegerField(blank=True, choices=[(1, '勤務'), (2, '欠勤'), (3, '休日'), (4, '休出（法定）'), (27, '休出（法定）午前休'), (14, '休出（法定）午後休（休息なし）'), (15, '休出（法定）午後休（休息あり）'), (5, '休出（法定外）'), (28, '休出（法定外）午前休'), (16, '休出（法定外）午後休（休息なし）'), (17, '休出（法定外）午後休（休息あり）'), (6, '有休'), (18, '有休-午前休'), (19, '有休-午後休（休息なし）'), (20, '有休-午後休（休息あり）'), (7, '代休'), (21, '代休-午前休'), (22, '代休-午後休（休息なし）'), (23, '代休-午後休（休息あり）'), (8, '特別休'), (24, '特別休-午前休'), (25, '特別休-午後休（休息なし）'), (26, '特別休-午後休（休息あり）'), (12, 'その他'), (13, '予定')], null=True)),
                ('extra_code', models.CharField(max_length=8)),
                ('accepted_overtime', models.BooleanField(default=False)),
                ('accepted_overwork_fromTime', models.DateTimeField(blank=True, null=True)),
                ('accepted_overwork_toTime', models.DateTimeField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=128, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sao.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10, unique=True, verbose_name='区分')),
                ('begin_time', models.TimeField(verbose_name='出社時間')),
                ('end_time', models.TimeField(verbose_name='退社時間')),
            ],
        ),
        migrations.AddField(
            model_name='appliedofficehours',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sao.Employee'),
        ),
        migrations.AddField(
            model_name='appliedofficehours',
            name='working_hours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sao.WorkingHour'),
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sao.TimeRecord')),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timerecord',
            name='rawFrom',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='timerecord',
            name='rawTo',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0, verbose_name='進捗')),
            ],
        ),
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
