# Generated by Django 5.0.3 on 2025-09-08 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyattendancerecord',
            old_name='actual_working_time',
            new_name='actual_work',
        ),
        migrations.RenameField(
            model_name='dailyattendancerecord',
            old_name='holiday_work',
            new_name='holiday',
        ),
        migrations.RenameField(
            model_name='dailyattendancerecord',
            old_name='late_time',
            new_name='late',
        ),
        migrations.RenameField(
            model_name='dailyattendancerecord',
            old_name='legal_holiday_work',
            new_name='legal_holiday',
        ),
        migrations.RenameField(
            model_name='dailyattendancerecord',
            old_name='night_work',
            new_name='night',
        ),
        migrations.RenameField(
            model_name='dailyattendancerecord',
            old_name='over_time',
            new_name='over',
        ),
    ]
