# Generated by Django 2.0 on 2019-12-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0001_squashed_0039_auto_20180611_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='enable_add_staff',
            field=models.BooleanField(default=False),
        ),
    ]
