# Generated by Django 3.0.2 on 2020-02-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0002_permission_enable_add_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='enable_import_time_record',
            field=models.BooleanField(default=False),
        ),
    ]
