# Generated by Django 5.0.3 on 2025-09-08 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0002_rename_actual_working_time_dailyattendancerecord_actual_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendancerecord',
            name='actual_work',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='dailyattendancerecord',
            name='early_leave',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='dailyattendancerecord',
            name='holiday',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='dailyattendancerecord',
            name='late',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='dailyattendancerecord',
            name='legal_holiday',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='dailyattendancerecord',
            name='night',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='dailyattendancerecord',
            name='over',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='dailyattendancerecord',
            name='over_8h',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='dailyattendancerecord',
            name='stepping_out',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
