# Generated by Django 3.0.2 on 2020-02-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0003_permission_enable_import_time_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='status',
            field=models.IntegerField(default=0, verbose_name='ステータス'),
        ),
    ]
