# Generated by Django 5.0.3 on 2025-09-12 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0003_alter_dailyattendancerecord_actual_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendancerecord',
            name='time_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='time_record', to='sao.employeedailyrecord'),
        ),
    ]
