# Generated by Django 3.0.2 on 2020-02-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0004_progress_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='message',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
