# Generated by Django 5.0.3 on 2025-09-13 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0004_alter_dailyattendancerecord_time_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverworkPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sao.employee')),
            ],
        ),
    ]
