# Generated by Django 5.0.3 on 2025-09-13 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0005_overworkpermission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OverworkPermission',
            new_name='OvertimePermission',
        ),
    ]
