# Generated by Django 3.0.2 on 2020-05-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0005_progress_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebTimeStamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
