# Generated by Django 5.0.3 on 2025-09-13 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0006_rename_overworkpermission_overtimepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimepermission',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
