# Generated by Django 3.0.2 on 2020-05-05 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0006_webtimestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='webtimestamp',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sao.Employee'),
        ),
        migrations.AddField(
            model_name='webtimestamp',
            name='stamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
