# Generated by Django 5.0.3 on 2025-09-13 12:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0007_overtimepermission_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedOvertimePayEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DurationField(default=datetime.timedelta(0))),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sao.employee')),
            ],
        ),
    ]
