# Generated by Django 3.0.2 on 2021-03-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0007_auto_20200505_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='SteppingOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_time', models.DateTimeField(blank=True, null=True)),
                ('return_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
