# Generated by Django 3.0.2 on 2021-04-02 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0008_steppingout'),
    ]

    operations = [
        migrations.AddField(
            model_name='steppingout',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sao.Employee'),
        ),
    ]
