# Generated by Django 5.0.3 on 2025-09-13 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0008_fixedovertimepayemployee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='include_overtime_pay',
        ),
        migrations.RemoveField(
            model_name='employeedailyrecord',
            name='is_overtime_work_permitted',
        ),
    ]
