# Generated by Django 3.0.2 on 2021-09-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0009_steppingout_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='enable_view_executive_section_page',
            field=models.BooleanField(default=False),
        ),
    ]
