# Generated by Django 5.0.3 on 2025-09-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0009_remove_employee_include_overtime_pay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendancerecord',
            name='working_hours_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyattendancerecord',
            name='working_hours_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyattendancerecord',
            name='status',
            field=models.IntegerField(choices=[(0, '未確定'), (1, '勤務'), (2, '欠勤'), (3, '休日'), (4, '休出（法定）'), (27, '休出（法定）午前休'), (14, '休出（法定）午後休（休息なし）'), (15, '休出（法定）午後休（休息あり）'), (5, '休出（法定外）'), (28, '休出（法定外）午前休'), (16, '休出（法定外）午後休（休息なし）'), (17, '休出（法定外）午後休（休息あり）'), (6, '有休'), (18, '有休-午前休'), (19, '有休-午後休（休息なし）'), (20, '有休-午後休（休息あり）'), (7, '代休'), (21, '代休-午前休'), (22, '代休-午後休（休息なし）'), (23, '代休-午後休（休息あり）'), (8, '特別休'), (24, '特別休-午前休'), (25, '特別休-午後休（休息なし）'), (26, '特別休-午後休（休息あり）'), (12, 'その他'), (13, '予定')], default=0),
        ),
    ]
