# Generated by Django 5.0.3 on 2024-03-13 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0001_squashed_0010_permission_enable_view_executive_section_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='enable_view_executive_section_page',
        ),
    ]
