# Generated by Django 5.0.3 on 2025-09-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0010_dailyattendancerecord_working_hours_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendancerecord',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
