# Generated by Django 5.0.3 on 2024-03-13 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0011_remove_permission_enable_view_executive_section_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='enable_access_secomcard',
        ),
    ]
