# Generated by Django 5.0.3 on 2025-09-13 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0011_dailyattendancerecord_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendancerecord',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='sao.employee'),
        ),
    ]
