# Generated by Django 5.0.3 on 2025-09-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0012_dailyattendancerecord_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendancerecord',
            name='clock_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
