# Generated by Django 5.0.3 on 2024-03-13 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0012_remove_permission_enable_access_secomcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='enable_import_time_record',
        ),
    ]
