# Generated by Django 5.0.3 on 2024-03-17 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0013_remove_permission_enable_import_time_record'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
