# Generated by Django 5.0.3 on 2025-09-13 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0013_alter_dailyattendancerecord_clock_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendancerecord',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='sao.employee'),
        ),
    ]
