# Generated by Django 5.0.3 on 2025-09-14 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0014_alter_dailyattendancerecord_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendancerecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='sao.employee'),
        ),
    ]
