# Generated by Django 5.0.3 on 2024-03-21 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0014_delete_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timerecord',
            name='extra_code',
        ),
    ]
