# Generated by Django 5.0.3 on 2024-03-21 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0015_remove_timerecord_extra_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timerecord',
            name='achievementFrom',
        ),
        migrations.RemoveField(
            model_name='timerecord',
            name='achievementTo',
        ),
    ]
