# Generated by Django 5.0.3 on 2025-09-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0016_alter_permission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendancerecord',
            name='overtime_permitted',
            field=models.BooleanField(default=False),
        ),
    ]
