# Generated by Django 5.0.3 on 2024-03-21 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0017_remove_timerecord_eval_code_timerecord_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timerecord',
            name='flag',
        ),
    ]
