# Generated by Django 5.0.3 on 2024-03-22 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0019_rename_fromtime_timerecord_clock_in_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timerecord',
            old_name='toTime',
            new_name='clock_out',
        ),
    ]
