# Generated by Django 5.0.3 on 2024-03-22 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0020_rename_totime_timerecord_clock_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timerecord',
            old_name='accepted_overtime',
            new_name='is_overtime_work_permitted',
        ),
    ]
