# Generated by Django 5.0.3 on 2024-03-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0021_rename_accepted_overtime_timerecord_is_overtime_work_permitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.IntegerField(choices=[(0, '一般'), (1, '開発')], default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.IntegerField(choices=[(0, '正社員'), (1, '派遣社員'), (2, '業務委託')], default=0),
        ),
    ]
