# Generated by Django 5.0.3 on 2024-03-25 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0022_alter_employee_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holiday',
            old_name='holiday',
            new_name='date',
        ),
    ]
