# Generated by Django 5.0.3 on 2024-03-29 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0023_rename_holiday_holiday_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timerecord',
            name='rawFrom',
        ),
        migrations.RemoveField(
            model_name='timerecord',
            name='rawTo',
        ),
    ]
