# Generated by Django 5.0.3 on 2024-03-29 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0024_remove_timerecord_rawfrom_remove_timerecord_rawto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timerecord',
            name='accepted_overwork_fromTime',
        ),
        migrations.RemoveField(
            model_name='timerecord',
            name='accepted_overwork_toTime',
        ),
    ]
