# Generated by Django 5.0.3 on 2025-08-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0025_remove_timerecord_accepted_overwork_fromtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinghour',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
