# Generated by Django 5.0.3 on 2025-08-28 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0026_workinghour_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppliedOfficeHours',
            new_name='EmployeeHour',
        ),
    ]
