# Generated by Django 5.0.3 on 2025-09-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0027_rename_appliedofficehours_employeehour'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaySwitchTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
