# Generated by Django 5.0.3 on 2025-09-03 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0028_dayswitchtime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeRecord',
            new_name='EmployeeDailyRecord',
        ),
    ]
