# Generated by Django 5.0.3 on 2025-09-05 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0001_squashed_0029_rename_timerecord_employeedailyrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjusted_clock_in', models.DateTimeField(blank=True, null=True)),
                ('adjusted_clock_out', models.DateField(blank=True, null=True)),
                ('actual_working_time', models.DurationField(blank=True, null=True)),
                ('late_time', models.DurationField(blank=True, null=True)),
                ('early_leave', models.DurationField(blank=True, null=True)),
                ('stepping_out', models.DurationField(blank=True, null=True)),
                ('out_of_time', models.DurationField(blank=True, null=True)),
                ('over_8h', models.DurationField(blank=True, null=True)),
                ('night_work', models.DurationField(blank=True, null=True)),
                ('legal_holiday_work', models.DurationField(blank=True, null=True)),
                ('holiday_work', models.DurationField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(0, '未確定'), (1, '勤務'), (2, '欠勤'), (3, '休日'), (4, '休出（法定）'), (27, '休出（法定）午前休'), (14, '休出（法定）午後休（休息なし）'), (15, '休出（法定）午後休（休息あり）'), (5, '休出（法定外）'), (28, '休出（法定外）午前休'), (16, '休出（法定外）午後休（休息なし）'), (17, '休出（法定外）午後休（休息あり）'), (6, '有休'), (18, '有休-午前休'), (19, '有休-午後休（休息なし）'), (20, '有休-午後休（休息あり）'), (7, '代休'), (21, '代休-午前休'), (22, '代休-午後休（休息なし）'), (23, '代休-午後休（休息あり）'), (8, '特別休'), (24, '特別休-午前休'), (25, '特別休-午後休（休息なし）'), (26, '特別休-午後休（休息あり）'), (12, 'その他'), (13, '予定')], null=True)),
                ('time_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_record', to='sao.employeedailyrecord')),
            ],
        ),
    ]
