# Generated by Django 5.0.3 on 2025-09-05 19:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0030_dailyattendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendancerecord',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='dailyattendancerecord',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dailyattendancerecord',
            name='time_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_record', to='sao.employeedailyrecord'),
        ),
    ]
