# Generated by Django 5.0.3 on 2025-09-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0031_dailyattendancerecord_create_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedailyrecord',
            name='scheduled_clock_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedailyrecord',
            name='scheduled_clock_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
