# Generated by Django 5.0.3 on 2025-09-06 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0032_employeedailyrecord_scheduled_clock_in_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedailyrecord',
            old_name='scheduled_clock_in',
            new_name='scheduled_end_time',
        ),
        migrations.RenameField(
            model_name='employeedailyrecord',
            old_name='scheduled_clock_out',
            new_name='scheduled_start_time',
        ),
    ]
