# Generated by Django 5.0.3 on 2025-09-07 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0033_rename_scheduled_clock_in_employeedailyrecord_scheduled_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedailyrecord',
            old_name='scheduled_end_time',
            new_name='working_hours_end',
        ),
        migrations.RenameField(
            model_name='employeedailyrecord',
            old_name='scheduled_start_time',
            new_name='working_hours_start',
        ),
    ]
