# Generated by Django 5.0.3 on 2025-09-07 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sao', '0034_rename_scheduled_end_time_employeedailyrecord_working_hours_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyattendancerecord',
            old_name='adjusted_clock_in',
            new_name='clock_in',
        ),
        migrations.RenameField(
            model_name='dailyattendancerecord',
            old_name='adjusted_clock_out',
            new_name='clock_out',
        ),
        migrations.RenameField(
            model_name='dailyattendancerecord',
            old_name='out_of_time',
            new_name='over_time',
        ),
    ]
