# Generated by Django 5.0.3 on 2025-09-04 00:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('accounts', '0001_initial'), ('accounts', '0002_remove_profile_avatar'), ('accounts', '0003_delete_profile')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
    ]
