# -*- coding: utf-8 -*-

"""
Django settings for sao_proj project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import logging
import logging.handlers
import os
from sys import argv
from dotenv import load_dotenv


if argv and 1 < len(argv):
    IS_TEST = "test" == argv[1]
else:
    IS_TEST = False

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# *DJANGO_SECRET_KEY has been moved to .env file*
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = IS_TEST or os.getenv("SAO_PROFILE")  == "dev"
ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "sao.apps.SaoConfig",
    "accounts.apps.AccountsConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "widget_tweaks",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "sao_proj.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "sao_proj.wsgi.application"


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": os.path.join(BASE_DIR, 'sao_db'),  # データベース名
#         "USER": "saoadmin",  # ユーザ名
#         "PASSWORD": "saoadmin",  # ぱすわど
#         "HOST": "",  # サーバのIPアドレスやホストを。空欄はローカルホスト
#         "PORT": "3306",
#     }
# }


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.environ.get('MYSQL_DATABASE'),  # データベース名
        "USER": os.environ.get('DJANGO_SUPERUSER_USERNAME'),  # ユーザ名
        "PASSWORD": os.environ.get('DJANGO_SUPERUSER_PASSWORD'),  # ぱすわど
        "HOST": os.environ.get('MYSQL_HOST',''),  # Dockerでは別ホストで動いてる
        "PORT": os.environ.get('MYSQL_PORT', '3306'),  # ポート番号",
        "TEST": {
            "NAME": "test_sao_db",  # テスト用のデータベース名
        },
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = "ja"

TIME_ZONE = "Asia/Tokyo"

USE_I18N = True

USE_L10N = True

# USE_TZ = True
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = (os.path.join(BASE_DIR, "assets/"),)
STATIC_ROOT = os.path.join(BASE_DIR, "static/")

LOGIN_URL = "accounts:login"
LOGOUT_REDIRECT_URL = "sao:home"

# django 1.10はデフォルトでSHA1をサポートしていない
PASSWORD_HASHERS = ["django.contrib.auth.hashers.SHA1PasswordHasher"]

# ログの設定
if os.environ.get("SAO_PROFILE") == "prod":
    LOGFILEDIR = "/var/log/sao"
else:
    LOGFILEDIR = os.path.join(BASE_DIR, "logs")
    if not os.path.exists(LOGFILEDIR):
        os.makedirs(LOGFILEDIR)
        print(f"Created log directory: {LOGFILEDIR}")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "dev": {
            "format": "\t".join(
                [
                    "[%(levelname)s]",
                    "%(asctime)s",
                    "%(module)s",
                    "%(message)s",
                ]
            )
        },
        "prod": {
            "format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
        },
    },
    "handlers": {
        "file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOGFILEDIR, "sao.log"),
            "formatter": "prod",
            "encoding": "utf-8",
            # 本番環境用のローテーション設定
            "maxBytes": 10 * 1024 * 1024,  # 10MB
            "backupCount": 5,
        } if os.environ.get('SAO_PROFILE') == 'prod' else { 
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": os.path.join(LOGFILEDIR, "sao.log"),
            "formatter": "dev",
            "encoding": "utf-8",  # これがないとユニコード文字列を出力してくれない
        },
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "dev",
        },
    },
    "loggers": {
        "sao": {
            "handlers": ["file", "console"],  # ← syslogを除去、fileを追加
            "level": "DEBUG", 
            "propagate": True
        },
        # Django全体のログも取得したい場合
        "django": {
            "handlers": ["file"],
            "level": "WARNING" if os.environ.get('SAO_PROFILE') == 'prod' else "INFO",
            "propagate": False,
        },
    },
    # ルートロガーの設定
    "root": {
        "handlers": ["console"] if os.environ.get('SAO_PROFILE') != 'prod' else [],
        "level": "WARNING",
    },
}

if IS_TEST:
    LOGGING["loggers"]['sao']['handlers'] = []


AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

# loggerは各モジュールで取得して使う
# logger = logging.getLogger("sao")
# この場所ではloggerはまだ出力できない
# logger.debug(
#     "sao is running"
# )

# ユーザーがアップロードしたファイルの保存先
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"
