# -*- coding: utf-8 -*-

"""
Django settings for sao_proj project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import logging
import logging.handlers
import os
from sys import argv

if argv and 1 < len(argv):
    IS_TEST = "test" == argv[1]
else:
    IS_TEST = False

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "^x0bff&csrgnpbot41985mfl*01seq=px*e48u)gwvn*-bju7k"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = IS_TEST or os.getenv("SAO_DEV") != 0
ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "sao.apps.SaoConfig",
    "accounts.apps.AccountsConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "widget_tweaks",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "sao_proj.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "sao_proj.wsgi.application"


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": os.path.join(BASE_DIR, 'sao_db'),  # データベース名
#         "USER": "saoadmin",  # ユーザ名
#         "PASSWORD": "saoadmin",  # ぱすわど
#         "HOST": "",  # サーバのIPアドレスやホストを。空欄はローカルホスト
#         "PORT": "3306",
#     }
# }


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "sao_db",  # データベース名
        "USER": "saoadmin",  # ユーザ名
        "PASSWORD": "saoadmin",  # ぱすわど
#        "HOST": "",  # サーバのIPアドレスやホストを。空欄はローカルホスト
        "HOST": "db",  # Dockerでは別ホストで動いてる
        "PORT": "3306",
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = "ja"

TIME_ZONE = "Asia/Tokyo"

USE_I18N = True

USE_L10N = True

# USE_TZ = True
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = (os.path.join(BASE_DIR, "assets/"),)
STATIC_ROOT = os.path.join(BASE_DIR, "static/")

LOGIN_URL = "accounts:login"
LOGOUT_REDIRECT_URL = "sao:home"

# django 1.10はデフォルトでSHA1をサポートしていない
PASSWORD_HASHERS = ["django.contrib.auth.hashers.SHA1PasswordHasher"]

# LOGFILEDIR = "/var/log/"
LOGFILEDIR = BASE_DIR
if DEBUG:
    LOGFILEDIR = BASE_DIR

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "dev": {
            "format": "\t".join(
                [
                    "[%(levelname)s]",
                    "%(asctime)s",
                    "%(module)s",
                    "%(message)s",
                    # "process:%(process)d",
                    # "thread:%(thread)d",
                ]
            )
        },
        "syslog": {"format": "%(levelname)s %(module)s %(message)s"},
    },
    "handlers": {
        "file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            # 'class': 'logging.handlers.SysLogHander',
            "filename": os.path.join(LOGFILEDIR, "sao.log"),
            "formatter": "dev",
            "encoding": "utf-8",  # これがないとユニコード文字列を出力してくれない
        },
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "dev",
        },
        "syslog": {
            "class": "logging.handlers.SysLogHandler",
            "address": "/dev/log",
            "facility": logging.handlers.SysLogHandler.LOG_LOCAL6,
            "formatter": "syslog",
        },
    },
    "loggers": {
        "sao": {"handlers": ["syslog", "console"], "level": "DEBUG", "propagate": True},
    },
}

if IS_TEST:
    LOGGING["loggers"]['sao']['handlers'] = []


AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

logger = logging.getLogger("sao")

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"
