CREATE DATABASE IF NOT EXISTS sao_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'saodb'@'%' IDENTIFIED BY 'saodb';
GRANT ALL PRIVILEGES ON sao_db.* TO 'saodb'@'%';
FLUSH PRIVILEGES;
