--  CREATE DATABASE IF NOT EXISTS test_sao_db CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER IF NOT EXISTS '${DJANGO_SUPERUSER_USERNAME}'@'%' IDENTIFIED BY '${DJANGO_SUPERUSER_PASSWORD}';
GRANT ALL PRIVILEGES ON *.* TO '${DJANGO_SUPERUSER_USERNAME}'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
